ReachingFam/Controllers/ReportController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ReachingFam.Core.Data;
using ReachingFam.Core.Enums;
using ReachingFam.Core.Interfaces;
using ReachingFam.Core.Models.ReachingFamViewModels;
using ReachingFam.Core.Services;

namespace ReachingFam.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly ILogger<ReportController> _logger;
        private readonly ApplicationDbContext _context;
        private readonly CustomIDataProtection _protector;
        private readonly IReportData _reportData;

        public ReportController(ILogger<ReportController> logger,
            ApplicationDbContext context,
            CustomIDataProtection protector,
            IReportData reportData
            )
        {
            _logger = logger;
            _context = context;
            _protector = protector;
            _reportData = reportData;
        }

        public async Task<IActionResult> Report()
        {
            var donorSummary = await _context.InwardItems.SumAsync(x => x.TotalWeight);
            return View();
        }

        public async Task<IActionResult> HampersReport()
        {
            return View(await _reportData.HampersReport());
        }

        public async Task<IActionResult> FullHamperReport()
        {
            return View(await _reportData.FullHamperReport());
        }

        public async Task<IActionResult> ThisWeekReport()
        {
            return View(_reportData.SummarizeReportData(await _reportData.SummaryReport(AnalyticPeriod.ThisWeek)));
        }

        public async Task<IActionResult> ThisMonthReport()
        {
            return View(_reportData.SummarizeReportData(await _reportData.SummaryReport(AnalyticPeriod.ThisMonth)));
        }

        public async Task<IActionResult> LastMonthReport()
        {
            return View(_reportData.SummarizeReportData(await _reportData.SummaryReport(AnalyticPeriod.LastMonth)));
        }

        public async Task<IActionResult> ThisYearReport()
        {
            return View(_reportData.SummarizeReportData(await _reportData.SummaryReport(AnalyticPeriod.ThisYear)));
        }

        [HttpGet]
        public async Task<IActionResult> SummaryReport(AnalyticPeriod period)
        {
            var summary = _reportData.SummarizeReportData(await _reportData.SummaryReport(period));
            summary.Period = period;

            return View(summary);
        }

        public async Task<IActionResult> GeneralReport(AnalyticPeriod period)
        {
            List<SummaryReportViewModel> reportedData = await _reportData.SummaryReport(period);

            //GraphViewModel graphView = new()
            //{
            //    FamilyHampers = reportedData.Select(x => x.Families).ToList(),
            //    PartnerHampers = reportedData.Select(x => x.Partners).ToList(),
            //    Donors = reportedData.Select(y => y.Donors).ToList(),
            //    Categories = reportedData.Select(k => k.Date).ToList()
            //};

            GraphViewModel graphView = new()
            {
                Families = [4, 2, 5, 5, 5, 8, 8, 6, 5, 8, 8, 6],
                Partners = [1, 3, 1, 4, 4, 9, 5, 8, 4, 9, 5, 8],
                Volunteers = [1, 3, 1, 4, 4, 9, 5, 8, 4, 9, 5, 8],
                Donors = [20, 29, 37, 36, 44, 45, 50, 58, 58, 60, 62, 65],
                FamilyHampersWeight = [520.22, 629.34, 937.34, 4336.66, 944.73, 845.22, 950.34, 458.23, 3258.52, 2260.52, 2262.43, 3465.52],
                PartnerHamperWeight = [20.22, 29.34, 37.34, 36.66, 44.73, 45.22, 50.34, 58.23, 58.52, 60.52, 62.43, 65.52],
                VolunteerHamperWeight = [20.22, 29.34, 37.34, 36.66, 44.73, 45.22, 50.34, 58.23, 58.52, 60.52, 62.43, 65.52],
                WeightIn = [20.22, 29.34, 37.34, 36.66, 44.73, 45.22, 50.34, 58.23, 58.52, 60.52, 62.43, 65.52],
                WeightOut = [20.22, 29.34, 37.34, 36.66, 44.73, 45.22, 50.34, 58.23, 58.52, 60.52, 62.43, 65.52],
                Hours = [20.22, 29.34, 37.34, 36.66, 44.73, 45.22, 50.34, 58.23, 58.52, 60.52, 62.43, 65.52],
                Wastes = [20.22, 29.34, 37.34, 36.66, 44.73, 45.22, 50.34, 58.23, 58.52, 60.52, 62.43, 65.52],
                Categories = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                Period = period
            };

            return View(graphView);
        }
    }
}

ReachingFam/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no" />
    <title>@ViewData["Title"] - Reaching Families</title>
    <meta content="Ayo Anegbe" name="author" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <!-- App favicon -->
    <link rel="shortcut icon" href="~/images/favicon.ico">

    <link href="~/libs/simple-datatables/style.css" rel="stylesheet" type="text/css" />
    <link href="~/libs/mobius1-selectr/selectr.min.css" rel="stylesheet" type="text/css" />
    <link href="~/libs/huebee/huebee.min.css" rel="stylesheet" type="text/css" />

    <!-- App css -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/app.min.css" rel="stylesheet" type="text/css" />
</head>
<body id="body">

    @await Html.PartialAsync("_LeftBarMenuPartial")

    @await Html.PartialAsync("_TopBarPartial")

    <div class="page-wrapper">

        <div class="page-content-tab">

            @RenderBody()

            <footer class="footer text-center text-sm-start">
                &copy; <script>
                            document.write(new Date().getFullYear())
                </script> Reaching Families Food Bank.
            </footer>
        </div>
         
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="~/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/libs/simplebar/simplebar.min.js"></script>
    <script src="~/libs/feather-icons/feather.min.js"></script>

    <script src="~/libs/mobius1-selectr/selectr.min.js"></script>
    <script src="~/libs/huebee/huebee.pkgd.min.js"></script>
     
    <script src="~/libs/simple-datatables/umd/simple-datatables.js"></script>
    <script src="~/js/pages/datatable.init.js"></script>

    <script src="~/libs/apexcharts/apexcharts.min.js"></script>
    <script src="~/js/pages/analytics-index.init.js"></script>

    <script src="~/js/pages/forms-advanced.js"></script>
    <script src="~/js/pages/form-validation.js"></script>
    <script src="~/lib/cryptography/aes.js"></script>

    <!-- App js -->
    <script src="~/js/app.js"></script>
    <script src="~/js/working_data.js"></script>
    <script src="~/js/app_common.js"></script>


    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ReachingFam/Views/Shared/_LeftBarMenuPartial.cshtml
@inject UserManager<ApplicationUser> UserManager

@{
    
    var user = await UserManager.GetUserAsync(User);
    var roles = new List<string> { "Super Administrator", "Administrator"};
}

<div class="leftbar-tab-menu">
    <div class="main-icon-menu">
        <a asp-controller="Home" asp-action="Index" class="logo logo-metrica d-block text-center">
            <span>
                <img src="~/images/rff-logo.png" alt="logo-small" class="logo-sm">
            </span>
        </a>
        <div class="main-icon-menu-body">
            <div class="position-reletive h-100" data-simplebar style="overflow-x: hidden;">
                <ul class="nav nav-tabs" role="tablist" id="tab-menu">
                    <li class="nav-item" data-bs-toggle="tooltip" data-bs-placement="right" title="Dashboard" data-bs-trigger="hover">
                        <a href="#MetricaDashboard" id="dashboard-tab" class="nav-link">
                            <i class="ti ti-smart-home menu-icon"></i>
                        </a><!--end nav-link-->
                    </li><!--end nav-item-->
                    <li class="nav-item" data-bs-toggle="tooltip" data-bs-placement="right" title="Setup" data-bs-trigger="hover">
                        <a href="#MetricaApps" id="apps-tab" class="nav-link">
                            <i class="ti ti-apps menu-icon"></i>
                        </a><!--end nav-link-->
                    </li><!--end nav-item-->                   
                    <li class="nav-item" data-bs-toggle="tooltip" data-bs-placement="right" title="Process Management" data-bs-trigger="hover">
                        <a href="#MetricaPages" id="pages-tab" class="nav-link">
                            <i class="ti ti-building-warehouse menu-icon"></i>
                        </a><!--end nav-link-->
                    </li><!--end nav-item-->
                    <li class="nav-item" data-bs-toggle="tooltip" data-bs-placement="right" title="Reports" data-bs-trigger="hover">
                        <a href="#MetricaUikit" id="uikit-tab" class="nav-link">
                            <i class="ti ti-files menu-icon"></i>
                        </a><!--end nav-link-->
                    </li><!--end nav-item-->
                    <li class="nav-item" data-bs-toggle="tooltip" data-bs-placement="right" title="User Management" data-bs-trigger="hover">
                        <a href="#MetricaAuthentication" id="authentication-tab" class="nav-link">
                            <i class="ti ti-shield-lock menu-icon"></i>
                        </a><!--end nav-link-->
                    </li><!--end nav-item-->
                </ul><!--end nav-->
            </div><!--end /div-->
        </div><!--end main-icon-menu-body-->
        <div class="pro-metrica-end">
            <a href="#" class="profile">
                <img src="~/images/users/user-vector.png" alt="profile-user" class="rounded-circle thumb-sm">
            </a>
        </div><!--end pro-metrica-end-->
    </div>
    <!--end main-icon-menu-->

    <div class="main-menu-inner">
        <!-- LOGO -->
        <div class="topbar-left">
            <a asp-controller="Home" asp-action="Index" class="logo">
                <span>
                    <img src="~/images/rff-logo-dark.png" alt=""  height="40">
                   @*  <img src="~/images/rff-logo-light.png" alt="logo-large" height="75"> *@
                </span>
            </a><!--end logo-->
        </div><!--end topbar-left-->
        <!--end logo-->
        <div class="menu-body navbar-vertical tab-content" data-simplebar>
            <div id="MetricaDashboard" class="main-icon-menu-pane tab-pane" role="tabpanel"
                aria-labelledby="dasboard-tab">
                <div class="title-box">
                    <h6 class="menu-title">Dashboard</h6>
                </div>
                
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Home" asp-action="Index">Analytics</a>
                    </li><!--end nav-item-->                    
                </ul><!--end nav-->
            </div><!-- end Dashboards -->

            <div id="MetricaApps" class="main-icon-menu-pane tab-pane" role="tabpanel"
                aria-labelledby="apps-tab">
                <div class="title-box">
                    <h6 class="menu-title">Setup</h6>
                </div>

                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Setup" asp-action="ListDonors">Donors</a>
                    </li><!--end nav-item-->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Setup" asp-action="ListFamilies">Families</a>
                    </li><!--end nav-item-->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Setup" asp-action="ListPartners">Partners</a>
                    </li><!--end nav-item-->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Setup" asp-action="ListUOMs">Unit of Measures</a>
                    </li><!--end nav-item-->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Setup" asp-action="ListOptionTypes">Option Types</a>
                    </li><!--end nav-item-->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Setup" asp-action="ListOptionValues">Option Values</a>
                    </li><!--end nav-item-->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Setup" asp-action="ListItemCategories">Item Categories</a>
                    </li>
                </ul><!--end nav-->
            </div><!-- end Crypto -->

            <div id="MetricaPages" class="main-icon-menu-pane tab-pane" role="tabpanel"
                 aria-labelledby="pages-tab">
                <div class="title-box">
                    <h6 class="menu-title">Process Management</h6>
                </div>

                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="InwardItemsList">Inward Items</a>
                    </li><!--end nav-item-->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="FamilyHamperList">Families Hampers</a>
                    </li><!--end nav-item-->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="PartnerGiveOutList">Partners Hampers</a>
                    </li><!--end nav-item-->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="VolunteerGiveOutList">Volunteers Hampers</a>
                    </li><!--end nav-item-->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="ItemsForCollection">Items For Collection</a>
                    </li><!--end nav-item-->
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="WastesList">Waste Management</a>
                    </li><!--end nav-item-->
                </ul><!--end nav-->

                <div class="title-box">
                    <h6 class="menu-title">Stock Management</h6>
                </div>
                
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="ListFoodItems">Food Items</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="ListStocks">Stock Items</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="AddStock">Add Stock</a>
                    </li>
                </ul>                

                <div class="title-box">
                    <h6 class="menu-title">Approvals</h6>
                </div>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="PendingApprovals">Pending Approvals</a>
                    </li>
                </ul>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="ItemsForApproval">All Approval Items</a>
                    </li>
                </ul>

                <div class="title-box">
                    <h6 class="menu-title">Gallery</h6>
                </div>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="ProcessManagement" asp-action="InwardItemsList">Inward Items</a>
                    </li>
                </ul>
            </div><!-- end Crypto -->

            <div id="MetricaUikit" class="main-icon-menu-pane tab-pane" role="tabpanel" aria-labelledby="pages-tab">
                <div class="title-box">
                    <h6 class="menu-title">Reports</h6>
                </div>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Report" asp-action="HampersReport">Family Hampers</a>
                    </li><!--end nav-item-->
                </ul>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Report" asp-action="SummaryReport" asp-route-Period="@AnalyticPeriod.ThisMonth">Summary Report</a>
                    </li><!--end nav-item-->
                </ul>
                <ul class="nav flex-column">
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Report" asp-action="GeneralReport" asp-route-Period="@AnalyticPeriod.ThisMonth">General Report</a>
                    </li><!--end nav-item-->
                </ul>
            </div>

            @if (await UserManager.IsInRoleAsync(user, "Super Administrator") || await UserManager.IsInRoleAsync(user, "Administrator"))
            {
                <div id="MetricaAuthentication" class="main-icon-menu-pane tab-pane" role="tabpanel"
                    aria-labelledby="authentication-tab">
                    <div class="title-box">
                        <h6 class="menu-title">User Management</h6>
                    </div>
                    @if (await UserManager.IsInRoleAsync(user, "Super Administrator"))
                    {
                        <ul class="nav flex-column">

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Register" asp-route-source="superAdmin">Register</a>
                            </li><!--end nav-item-->
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="GetAllUsers">Users List</a>
                            </li><!--end nav-item-->
                            
                        </ul>

                        <!--end nav-->
                    }
                    else
                    {
                        <ul class="nav flex-column">

                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="Register" asp-route-source="admin">Register</a>
                            </li><!--end nav-item-->
                            <li class="nav-item">
                                <a class="nav-link" asp-controller="Account" asp-action="UserList">Users List</a>
                            </li><!--end nav-item-->

                        </ul>

                        <!--end nav-->
                    }

                </div><!-- end Authentication-->
            }

            
        </div>
        <!--end menu-body-->
    </div><!-- end main-menu-inner-->
</div>
        

ReachingFam/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!-- App favicon -->
    <link rel="shortcut icon" href="~/images/favicon.ico">

    <!-- App css -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/icons.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/app.min.css" rel="stylesheet" type="text/css" />
</head>
<body id="body" class="auth-page" style="background-image: url('~/images/p-1.png'); background-size: cover; background-position: center center;">
    <div>
        @RenderBody()
    </div>

    <!-- vendor js -->    
    <script src="~/libs/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/libs/simplebar/simplebar.min.js"></script>
    <script src="~/libs/feather-icons/feather.min.js"></script>
    <!-- App js -->
    <script src="~/js/app.js"></script>
</body>
</html>

ReachingFam/Views/Shared/_TopBarPartial.cshtml
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@{
    var user = await UserManager.GetUserAsync(User);
    
}

<div class="topbar">
    <!-- Navbar -->
    <nav class="navbar-custom" id="navbar-custom">

        @if (SignInManager.IsSignedIn(User))
        {
            var role = await UserManager.GetRolesAsync(user);

            <ul class="list-unstyled topbar-nav float-end mb-0">

                <li class="dropdown">
                    <a class="nav-link dropdown-toggle nav-user" data-bs-toggle="dropdown" href="#" role="button"
                       aria-haspopup="false" aria-expanded="false">
                        <div class="d-flex align-items-center">
                            <img src="~/images/users/avatar.png" alt="profile-user" class="rounded-circle me-2 thumb-sm" />
                            <div>
                                <small class="d-none d-md-block font-11">@role.FirstOrDefault()</small>
                                <span class="d-none d-md-block fw-semibold font-12">
                                    @user?.FirstName <i class="mdi mdi-chevron-down"></i>
                                </span>
                            </div>
                        </div>
                    </a>
                    <div class="dropdown-menu dropdown-menu-end">
                        <a class="dropdown-item" href="#"><i class="ti ti-user font-16 me-1 align-text-bottom"></i> Profile</a>
@*                         <a class="dropdown-item" href="#"><i class="ti ti-settings font-16 me-1 align-text-bottom"></i> Settings</a> *@
                        <div class="dropdown-divider mb-0"></div>
                        <a class="dropdown-item" asp-controller="Account" asp-action="Lockout"><i class="ti ti-power font-16 me-1 align-text-bottom"></i> Logout</a>
                    </div>
                </li><!--end topbar-profile-->

            </ul>
        }

        <ul class="list-unstyled topbar-nav mb-0">
            <li>
                <button class="nav-link button-menu-mobile nav-icon" id="togglemenu">
                    <i class="ti ti-menu-2"></i>
                </button>
            </li>
            <li class="hide-phone app-search">
                <form role="search" action="#" method="get">
                    <input type="search" name="search" class="form-control top-search mb-0" placeholder="Type text...">
                    <button type="submit"><i class="ti ti-search"></i></button>
                </form>
            </li>
        </ul>
    </nav>
    <!-- end navbar-->
</div>